version: "3"
services:
  web:
    build: .
    environment:
        DB_URL: mongodb://mongo:27017/fortunate_prod_db
        PORT: 3001
    ports:
        - "3001:3001"
    depends_on:
        - mongo
  mongo:
          image: mongo
          ports:
              - "27017:27017"